import { Suspense } from 'react';
import { SearchResults } from './SearchResults';
import { SearchBox } from '@/components/aem/SearchBox';

/**
 * Search is query-dependent, so it is rendered on the client from /products.json (generated by the snapshot
 * crawler; in live mode `npm run snapshot:products` refreshes it). This keeps the page cacheable/static —
 * the same reasoning the dispatcher applies: never cache per-query HTML, move the query to the client.
 */
export const metadata = { title: 'Search | BlueShelf' };

export default function SearchPage() {
  return (
    <>
      <SearchBox placeholder="Search products" />
      <Suspense fallback={<p className="muted">Loading…</p>}><SearchResults /></Suspense>
    </>
  );
}
